doctrine:
    dbal:
        
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
            

    

    
parameters:            
    logo_directory: '%kernel.project_dir%/web/uploads/logos'
    company_directory: '%kernel.project_dir%/web/uploads/companies'