maciej_switch:
   path: /maciej
   defaults: { _controller: MaciejBundle:Default:show}
    
maciej_companyform:
    path:       /maciej/companyform
    defaults: { _controller: MaciejBundle:Companies:form}

maciej_companylist:
    path:       /maciej/companylist
    defaults: { _controller: MaciejBundle:Companies:list}
    
maciej_companyedit:
    path:  /maciej/companyedit/{wild}
    defaults: { _controller: MaciejBundle:Companies:edit}
    
maciej_companydelete:
    path: /maciej/companydelete/{wild}
    defaults: { _controller: MaciejBundle:Companies:delete}
    
maciej_companydeleteimage:
    path: /maciej/gamesdit/delimg/{wild}
    defaults: { _controller: MaciejBundle:Companies:delimg}
    
maciej_gamesform:
    path:     /maciej/gamesform
    defaults: { _controller: MaciejBundle:Games:show}
    
maciej_gameslist:
    path: /maciej/gameslist
    defaults: { _controller: MaciejBundle:Games:list}
   
maciej_gamesedit:
    path: /maciej/gamesedit/{wild}
    defaults: { _controller: MaciejBundle:Games:edit}
    
maciej_gamesdeleteimage:
    path: /maciej/gamesdit/delimg/{wild}
    defaults: { _controller: MaciejBundle:Games:delimg}
    
maciej_gamesimageform:
    path: /maciej/gamesimageform
    defaults : { _controller: MaciejBundle:GameImage:show}
    
maciej_gamesimagelist:
    path: /maciej/gamesimagelist/{wild}
    defaults: { _controller: MaciejBundle:GameImage:list}
    
maciej_gameimagedelete:
    path: /maciej/gamesimagedelete/{wild}
    defaults: { _controller: MaciejBundle:GameImage:delete}
    
maciej_gamesimage1form:
    path: /maciej/gamesimageform1
    defaults : { _controller: MaciejBundle:GameImage1:show}
    
maciej_gamesimage1list:
    path: /maciej/gamesimagelist1/{wild}
    defaults: { _controller: MaciejBundle:GameImage1:list}
    
maciej_gameimage1delete:
    path: /maciej/gamesimagedelete1/{wild}
    defaults: { _controller: MaciejBundle:GameImage1:delete}
    

    

  
 

    