maciej_switch:
   path: /maciej
   defaults: { _controller: MaciejBundle:Default:show}
    
maciej_companyform:
    path:       /maciej/companyform
    defaults: { _controller: MaciejBundle:Companies:form}

maciej_companylist:
    path:       /maciej/companylist
    defaults: { _controller: MaciejBundle:Companies:list}
    
maciej_companyedit:
    path:  /maciej/companyedit
    defaults: { _controller: MaciejBundle:Companies:edit}
    
maciej_companydelete:
    path: /maciej/companydelete
    defaults: { _controller: MaciejBundle:Companies:delete}
    
maciej_gamesform:
    path:     /maciej/gamesform
    defaults: { _controller: MaciejBundle:Games:show}
    
maciej_gameslist:
    path: /maciej/gameslist
    defaults: { _controller: MaciejBundle:Games:list}
   
maciej_gamesedit:
    path: /maciej/gamesedit
    defaults: { _controller: MaciejBundle:Games:edit}
    

  
 

    