maciej_switch:
   path: /maciej
   defaults: { _controller: MaciejBundle:Default:show}
    
maciej_first:
    path:       /maciej/first
    defaults: { _controller: MaciejBundle:First:show}

maciej_second:
    path:       /maciej/second
    defaults: { _controller: MaciejBundle:Second:show}
    
maciej_form:
    path:     /maciej/form
    defaults: { _controller: MaciejBundle:Games:show}
    
maciej_list:
    path: /maciej/list
    defaults: { _controller: MaciejBundle:Games:list}
   
maciej_edit:
    path: /maciej/edit
    defaults: { _controller: MaciejBundle:Games:edit}
    

  
 

    