
maciej_switch:
    path:       /maciej
    defaults: { _controller: MaciejBundle:Switch:show }
    

    
maciej_first:
    path:       /maciej/{wild}
    defaults: { _controller: MaciejBundle:First:show}
    requirements: 
         wild: first
         
maciej_second:
    path:       /maciej/{wild}
    defaults: { _controller: MaciejBundle:Second:show}
    requirements: 
         wild: second
    
maciej_form:
    path:     /maciej/{wild}
    defaults: { _controller: MaciejBundle:Form:show}
    requirements:
        wild: form
    
maciej_submit:
    path:   /maciej/{wild}
    defaults: { _controller: MaciejBundle:Form:submit}

    