services:
    switch:
        class: MaciejBundle\Controller\SwitchController
#    maciej.example:
#        class: MaciejBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    MaciejBundle\Service\FileUploader:
        arguments:
            $targetDir:   '%logo_directory%'