services:
    MaciejBundle\Service\FileUploader:
        arguments:
            $targetDir:   '%logo_directory%'
            $targetDirCompany:   '%company_directory%'
            $targetDirGameImage: '%gameimage_directory%'